'use client';

import { useState } from 'react';

const departments = [
  ['Cardiology', 'Heart care', 'Routine to advanced cardiac consultations and diagnostics.'],
  ['Orthopaedics', 'Bone & joint', 'Movement, injury and joint-care support for every age.'],
  ['Obstetrics & Gynaecology', 'Women’s health', 'Compassionate care through every stage of life.'],
  ['General Medicine', 'Everyday care', 'Trusted diagnosis, treatment and preventive care.'],
];
const services = [
  ['01', 'Find a specialist', 'Explore departments, procedures and the right doctor for your care.'],
  ['02', 'Book an appointment', 'Send an appointment request and receive a call-back from our team.'],
  ['03', 'Plan your visit', 'Get practical guidance for OPD, admissions, insurance and patient support.'],
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);
  return <main>
    <div className="topline"><span>24×7 Emergency Care</span><span>Jagatpura, Jaipur · Rajasthan 302012</span></div>
    <header className="nav-shell"><a href="#home" className="brand" aria-label="BST Hospital home"><img src="/bst-logo.png" alt="Dr. B. S. Tomar Institute of Medical Sciences & Research and Hospital" /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">☰</button><nav className={menuOpen ? 'nav open' : 'nav'}><a href="#about">About</a><a href="#departments">Departments</a><a href="#doctors">Doctors</a><a href="#patient-care">Patient Care</a><a href="#contact">Contact</a><a href="#appointment" className="nav-cta">Book appointment</a></nav></header>
    <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">A unit associated with NIMS</p><h1>Care that listens.<br /><em>Healing that lasts.</em></h1><p className="hero-text">Compassionate, patient-first healthcare from a trusted multidisciplinary team in Jagatpura, Jaipur.</p><div className="hero-actions"><a href="#appointment" className="button primary">Request appointment <span>→</span></a><a href="#departments" className="text-link">Explore specialties <span>↘</span></a></div></div><div className="hero-art" aria-hidden="true"><div className="sun-disc"></div><div className="cross-mark">+</div><div className="care-card"><span>Patient-first care</span><strong>Here when you need us.</strong></div></div><div className="hero-strip"><div><b>24×7</b><span>Emergency support</span></div><div><b>Multi-speciality</b><span>Coordinated care</span></div><div><b>Jagatpura</b><span>Jaipur, Rajasthan</span></div></div></section>
    <section className="intro section" id="about"><p className="eyebrow red">WELCOME TO BST HOSPITAL</p><div className="intro-grid"><h2>Modern medicine,<br />deeply human care.</h2><div><p className="lead">At Dr. B. S. Tomar Institute of Medical Sciences & Research and Hospital, we bring together clinical expertise, clear communication and a caring environment—so every patient feels understood.</p><a href="#patient-care" className="under-link">How we support your visit <span>→</span></a></div></div></section>
    <section className="department-section section" id="departments"><div className="section-heading"><div><p className="eyebrow red">CLINICAL SPECIALITIES</p><h2>Care for every chapter<br />of your health.</h2></div><p>Our clinical teams work together to help you find answers, treatment and confidence—under one roof.</p></div><div className="department-grid">{departments.map(([name, kind, description]) => <article className="department-card" key={name}><span className="card-number">{kind}</span><h3>{name}</h3><p>{description}</p><a href="#appointment">Learn more <span>→</span></a></article>)}</div></section>
    <section className="doctor-banner" id="doctors"><div><p className="eyebrow light">THE RIGHT DOCTOR, MADE EASIER</p><h2>Expert guidance begins<br />with a conversation.</h2><p>Find the right department and share your requirement. Our team will guide you to the appropriate specialist.</p><a href="#appointment" className="button pale">Find a doctor <span>→</span></a></div><div className="doctor-orbit" aria-hidden="true"><div className="orbit-core">BST<br /><small>CARE</small></div><span className="orb orb-one">✦</span><span className="orb orb-two">♥</span><span className="orb orb-three">+</span></div></section>
    <section className="section patient-section" id="patient-care"><p className="eyebrow red">PATIENT SERVICES</p><div className="section-heading patient-heading"><h2>Clear support,<br />at every step.</h2><p>From your first question to follow-up care, we help make your experience simpler and more reassuring.</p></div><div className="service-list">{services.map(([num, title, text]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div><b>→</b></article>)}</div></section>
    <section className="appointment" id="appointment"><div className="appointment-copy"><p className="eyebrow light">APPOINTMENTS</p><h2>Let’s take the next step together.</h2><p>Tell us what you need. Our patient-support team will get in touch to help with your appointment.</p><div className="appointment-note"><span>✦</span><p>For urgent medical emergencies, please visit the nearest emergency department immediately.</p></div></div><form onSubmit={(e) => { e.preventDefault(); setSent(true); }}><label>Your name<input required placeholder="Enter your name" /></label><label>Phone number<input required type="tel" placeholder="Enter your phone number" /></label><label>How can we help?<select defaultValue=""><option value="" disabled>Select a department or service</option><option>Find a specialist</option><option>Book an appointment</option><option>Patient services</option></select></label><button className="button primary" type="submit">{sent ? 'Request received ✓' : 'Request a call-back →'}</button>{sent && <p className="form-success">Thank you. Our team will contact you shortly.</p>}</form></section>
    <footer id="contact"><div className="footer-top"><img src="/bstims-logo.png" alt="Dr B S Tomar Institute of Medical Sciences & Research" /><p>Trusted care, close to home.</p><a href="#appointment" className="button primary">Book appointment →</a></div><div className="footer-bottom"><span>© 2026 BST Hospital. All rights reserved.</span><span>Jagatpura, Jaipur · Rajasthan</span><a href="#home">Back to top ↑</a></div></footer>
  </main>;
}
